In [1]:
from qutip import *
import numpy as np

In [2]:
levels = 5
np.diag(np.arange(0, levels))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [3]:
create(levels)*destroy(levels)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]

In [5]:
 np.diag(np.sqrt(np.arange(1, levels)), 1)+np.diag(np.sqrt(np.arange(1, levels)), -1)

array([[0.        , 1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 1.41421356, 0.        , 0.        ],
       [0.        , 1.41421356, 0.        , 1.73205081, 0.        ],
       [0.        , 0.        , 1.73205081, 0.        , 2.        ],
       [0.        , 0.        , 0.        , 2.        , 0.        ]])

In [10]:
a = create(levels) + destroy(levels)
print(a.data)

  (0, 1)	(1+0j)
  (1, 0)	(1+0j)
  (1, 2)	(1.4142135623730951+0j)
  (2, 1)	(1.4142135623730951+0j)
  (2, 3)	(1.7320508075688772+0j)
  (3, 2)	(1.7320508075688772+0j)
  (3, 4)	(2+0j)
  (4, 3)	(2+0j)
