In [1]:
# To find ECD Control

import sys 
sys.path.append('C:\\Users\\Eesh Gupta\\Documents\\RU Research\\Chakram')


In [31]:
import numpy as np
from qutip import *
from ECD_batch_optimizerV1 import BatchOptimizer
from Simulation_Classes_Single_ModeV4 import *
import matplotlib.pyplot as plt
import tfq_quantum as tfq
import tensorflow as tf

In [3]:
%load_ext autoreload
%autoreload 2

In [338]:
#The target oscillator state.
N =5
Fock = 1
psi_i = tensor(basis(2,0), basis(N,0)) # initial state
psi_t = tensor(basis(2,0), basis(N,Fock)) #target state

In [339]:
#Optimization of ECD Circuit parameters (betas, phis, and thetas)
#the optimization options
opt_params = {
'N_blocks' : 1, #circuit depth
'N_multistart' : 1, #Batch size (number of circuit optimizations to run in parallel)
'epochs' : 500, #number of epochs before termination
'epoch_size' : 10, #number of adam steps per epoch
'learning_rate' : 0.01, #adam learning rate
'term_fid' : 0.999, #terminal fidelitiy
'dfid_stop' : 1e-6, #stop if dfid between two epochs is smaller than this number
'beta_scale' : 3.0, #maximum |beta| for random initialization
'initial_states' : [psi_i], #qubit tensor oscillator, start in |g> |0>
'target_states' : [psi_t], #end in |e> |target>.
'name' : 'Fock %d' % Fock, #name for printing and saving
'filename' : None, #if no filename specified, results will be saved in this folder under 'name.h5'
}


#note: optimizer includes pi pulse in every ECD step. However, final ECD step is implemented 
#in experiment as a displacement since the qubit and oscillator should be disentangled at this point.
#So, we ask the optimizer to end in |e> |target> instead of |g>|target>.

In [340]:
opt = BatchOptimizer(**opt_params)
opt.print_info()

Tensor("alphas:0", shape=(1, 1), dtype=complex64)
optimization_type: state transfer
N_multistart: 1
N_blocks: 1
term_fid: 0.999
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 5
filename: Fock 1.h5

Best circuit parameters found:
betas:         [0.27743-0.28953j]
alphas:        [0.+0.j]
phis (deg):    [0.]
thetas (deg):  [155.8505]
Max Fidelity:  0.036926




In [172]:
opt.optimize()

Start time: 2023-01-06 10:44:20
 Epoch: 28 / 500 Max Fid: 0.368175 Avg Fid: 0.368175 Max dFid: 0.000001 Avg dFid: 0.000001 Elapsed time: 0:00:04.968746 Remaing time: 0:01:23.758868
 max dFid: 0.000001
dFid stop: 0.000001


 Optimization stopped.  No dfid is greater than dfid_stop

optimization_type: state transfer
N_multistart: 1
N_blocks: 2
term_fid: 0.999
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 5
filename: Fock 1.h5

Best circuit parameters found:
betas:         [-0.27784-0.0625j   0.42633-1.93618j]
alphas:        [0.+0.j]
phis (deg):    [0.      0.18166]
thetas (deg):  [ 113.50295 -113.48418]
Max Fidelity:  0.368175


termination reason: dfid
optimization timestamp (start time): 2023-01-06 10:44:20
timestamp (end time): 2023-01-06 10:44:25
elapsed time: 0:00:04.971254
Time per epoch (epoch s

'2023-01-06 10:44:20'

In [206]:
a = 1
b = np.array(a)
len(b.shape)

0

In [207]:
opt_params['user_angles'] = np.loadtxt('test.txt')
opt = BatchOptimizer(**opt_params)
opt.print_info()

C:\Users\Eesh Gupta\Documents\RU Research\Chakram\Multimode-Conditional-Displacements\hpc_runs\single_mode_ecd\Initialization SNAP trick\ECD_batch_optimizerV1.py:153: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (filename is not None and filename is not "")
C:\Users\Eesh Gupta\Documents\RU Research\Chakram\Multimode-Conditional-Displacements\hpc_runs\single_mode_ecd\Initialization SNAP trick\ECD_batch_optimizerV1.py:658: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  time_per_epoch = elapsed_time_s / epoch if epoch is not 0 else 0.0



Need tf version 2.3.0 or later. Using tensorflow version: 2.7.0

after
[[-1.89125371]]
after
[[-0.6587857]]
after
[[0.]]
after
[[3.13897014]]
Tensor("alphas:0", shape=(1, 1), dtype=complex64)
optimization_type: state transfer
N_multistart: 1
N_blocks: 1
term_fid: 0.999
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: [-1.89125 -0.65879  0.       3.13897]
N_cav: 5
filename: Fock 1.h5

Best circuit parameters found:
betas:         [-1.49548+1.15774j]
alphas:        [0.+0.j]
phis (deg):    [0.]
thetas (deg):  [179.84975]
Max Fidelity:  0.364938




In [163]:
opt.betas_rho

<tf.Variable 'betas_rho:0' shape=(3, 1) dtype=float32, numpy=
array([[1.8888146 ],
       [0.81543046],
       [0.55811137]], dtype=float32)>

In [70]:
opt.best_fidelity()

0.37674236

In [71]:
end_idx = 1
bs = opt.batch_construct_block_operators(opt.betas_rho,
                                            opt.betas_angle, 
                                            opt.alphas_rho,
                                             opt.alphas_angle,
                                             opt.phis, opt.thetas)
tf_initial_state = tfq.qt2tf(psi_i)
psis = tf.stack([tf_initial_state] * opt.parameters["N_multistart"])
for U in bs[:end_idx + 1]: 
    psis = tf.einsum(
            "mij,mjk->mik", U, psis
        )  # m: multistart

In [74]:
bs[1]

<tf.Tensor: shape=(1, 10, 10), dtype=complex64, numpy=
array([[[-0.4808389 -4.5728692e-01j,  0.41558307+3.5895973e-02j,
         -0.15420058+1.0302689e-01j,  0.02098544-6.4561494e-02j,
          0.00590413+1.9527098e-02j,  0.4829354 +2.8936111e-07j,
         -0.23717344+1.8950371e-01j,  0.02964935-1.3167311e-01j,
          0.02131334+4.4573583e-02j, -0.01290748-7.3369886e-03j],
        [-0.05668175-4.1326764e-01j, -0.29058304-2.7669156e-01j,
          0.47085094+3.8995802e-02j, -0.23893887+1.5802522e-01j,
          0.05060502-1.0433913e-01j,  0.23716597+1.8952022e-01j,
          0.29202136+1.8030265e-04j, -0.26787528+2.1558838e-01j,
          0.04675432-2.0317833e-01j,  0.02564295+8.0407105e-02j],
        [ 0.09492427-1.5930417e-01j, -0.06541561-4.6814656e-01j,
         -0.13417114-1.2189893e-01j,  0.49684113+2.7149886e-02j,
         -0.3255015 +9.7482346e-02j,  0.02983745+1.3162272e-01j,
          0.2692964 +2.1408179e-01j,  0.13189714-3.0061791e-03j,
         -0.27564067+2.3487096e-0

In [37]:
psi_i

Quantum object: dims = [[2, 5], [1, 1]], shape = (10, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [36]:
tfq.tf2qt(psis[0])

Quantum object: dims = [[2, 5], [1, 1]], shape = (10, 1), type = ket
Qobj data =
[[ 6.28828138e-06+6.06607139e-01j]
 [-1.99913651e-01+5.72838664e-01j]
 [-2.67409891e-01+3.34334314e-01j]
 [-2.05054089e-01+1.36915728e-01j]
 [ 1.58984773e-02+1.39937624e-01j]
 [-9.99395968e-04-1.03600541e-08j]
 [ 9.43720981e-04+3.29071394e-04j]
 [-5.47959993e-04-4.40120202e-04j]
 [ 2.32088292e-04+3.67655826e-04j]
 [-9.66434745e-05-1.55807007e-04j]]

In [319]:
def new_initial_state(end_idx, N, initial_state, angles_filename): 
    '''
    Returns U_{i-1} * U_{i-2} * ... * U_1 * initial state
    where U is the layer matrix and i-1 = end_index
    '''
    #edge case
    if end_idx < 0: 
        return initial_state
    #normal code
    opt_params_ = opt_params.copy()
    opt_params_['N_blocks'] = N
    opt_params_['N_multistart'] = 1
    opt_params_['user_angles'] = np.loadtxt(angles_filename)
    
    opt = BatchOptimizer(**opt_params_)
    bs = opt.batch_construct_block_operators(opt.betas_rho,
                                            opt.betas_angle, 
                                            opt.alphas_rho,
                                             opt.alphas_angle,
                                             opt.phis, opt.thetas)
    tf_initial_state = tfq.qt2tf(initial_state)
    psis = tf.stack([tf_initial_state] * opt.parameters["N_multistart"])
    for k in range(end_idx + 1): 
        U = bs[k]
        psis = tf.einsum(
                "mij,mjk->mik", U, psis
            )  # m: multistart
    return tfq.tf2qt(psis[0])
    

In [189]:
angles_filename = 'test.txt'
# start_idx =0
# N = 2
# opt_params_ = opt_params.copy()
# opt_params_['N_blocks'] = N 
# opt_params_['N_multistart'] = 1
# opt_params_['user_angles'] = np.loadtxt(angles_filename)
# print(np.loadtxt(angles_filename))


# opt = BatchOptimizer(**opt_params_)
# bs = opt.batch_construct_block_operators(opt.betas_rho,
#                                         opt.betas_angle, 
#                                         opt.alphas_rho,
#                                          opt.alphas_angle,
#                                          opt.phis, opt.thetas)

[[ 0.53142399  1.89094746]
 [ 1.93092418 -0.65922534]
 [ 0.          0.        ]
 [ 3.1384871  -3.13625121]]
Tensor("alphas:0", shape=(1, 1), dtype=complex64)
Tensor("alphas:0", shape=(2, 1), dtype=complex64)


In [190]:
# opt.parameters['N_blocks']

2

In [275]:
def new_final_state(start_idx, N, final_state, angles_filename): 
    '''
    Returns Udag_{i} * Udag_{i+1} * ... * U_N * final state
    where U is the layer matrix and i= start_index
    '''
    print('N ' + str(N))
    print('start_idx ' + str(start_idx))
    opt_params_ = opt_params.copy()
    opt_params_['N_blocks'] = N 
    opt_params_['N_multistart'] = 1
    opt_params_['user_angles'] = np.loadtxt(angles_filename)
    print(np.loadtxt(angles_filename))

    
    opt = BatchOptimizer(**opt_params_)
    bs = opt.batch_construct_block_operators(opt.betas_rho,
                                            opt.betas_angle, 
                                            opt.alphas_rho,
                                             opt.alphas_angle,
                                             opt.phis, opt.thetas)
    tf_final_state = tfq.qt2tf(final_state)
    psis = tf.stack([tf_final_state] * opt.parameters["N_multistart"])
    for k in range(N-start_idx):
#         print(len(bs[start_idx:]))
#         print(N - start_idx - 1 - k)
             
        U = bs[N - 1 - k]
        #complex conjuagte U 
        U_t = tf.einsum("mij -> mji", U) # transpose
        U_dag = tf.math.conj(U_t)
        psis = tf.einsum(
                "mij,mjk->mik", U_dag, psis
            )  # m: multistart
    return tfq.tf2qt(psis[0])
    

In [193]:
a = [1,2,3]
a[1:]

[2, 3]

In [222]:
a = [1,2,3]
np.asarray(a)

array([1, 2, 3])

In [194]:
def random_int(N = 1): 
    '''
    returns a random number between 0 and N-1
    '''
    if N == 0 or N ==1: 
        return 0
    rng = np.random.default_rng(12345)
    return rng.integers(low=0, high=N-1, size=1)[0]

In [225]:
def main(initial_state, final_state, 
         angles_filename = 'test.txt', new_angles_filename = 'test1.txt',
         threshold = 0.9): 
    '''
    Return good initial parama nd layer count 
    '''
    # first insert 1 layer
    opt_params_ = opt_params.copy()
    opt_params_['N_blocks'] = 1
    opt_params_['N_multistart'] = 1
    opt_params_['initial_states'] = [initial_state]
    opt_params_['target_states'] = [final_state]
    opt = BatchOptimizer(**opt_params_)
    opt.optimize()
    opt.save_angles(angles_filename)
    fid = opt.best_fidelity()
    
    
    N = 1 #depth
    
    #now add more layers
    while fid < threshold: 
        insert_idx = random_int(N)
        new_in_state = new_initial_state(insert_idx-1, N, 
                                         initial_state, 
                                         angles_filename)
        new_fin_state = new_final_state(insert_idx, N, final_state, 
                                         angles_filename)
        #only optimize new layer        
        opt_params_ = opt_params.copy()
        opt_params_['N_blocks'] = 1
        opt_params_['N_multistart'] = 1
        opt_params_['initial_states'] = [new_in_state]
        opt_params_['target_states'] = [new_fin_state]
        opt_params_['user_angles'] =np.asarray([0.0,0.0,0.0,np.pi])
        opt = BatchOptimizer(**opt_params_)
        opt.optimize()
        opt.save_angles(new_angles_filename)
        #update angles
        angles_filename = insert_angles(insert_idx,
                                        angles_filename,
                                        new_angles_filename)
        print('Now angles are ')
        print(np.loadtxt(angles_filename))
        fid = opt.best_fidelity()
        
        N+=1
    return N, fid, angles_filename

In [341]:
initial_state = psi_i
final_state = psi_t 
angles_filename = 'test.txt'
opt_params_ = opt_params.copy()
opt_params_['N_blocks'] = 1
opt_params_['N_multistart'] = 1
opt_params_['initial_states'] = [initial_state]
opt_params_['target_states'] = [final_state]
opt = BatchOptimizer(**opt_params_)
opt.optimize()
opt.save_angles(angles_filename)
fid = opt.best_fidelity()

Start time: 2023-01-06 14:57:00
Tensor("alphas:0", shape=(1, 1), dtype=complex64)
 Epoch: 33 / 500 Max Fid: 0.368111 Avg Fid: 0.368111 Max dFid: 0.000001 Avg dFid: 0.000001 Elapsed time: 0:00:05.845474 Remaing time: 0:01:22.722314
 max dFid: 0.000001
dFid stop: 0.000001


 Optimization stopped.  No dfid is greater than dfid_stop

optimization_type: state transfer
N_multistart: 1
N_blocks: 1
term_fid: 0.999
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 5
filename: Fock 1.h5

Best circuit parameters found:
betas:         [-1.89103+0.65942j]
alphas:        [0.+0.j]
phis (deg):    [0.]
thetas (deg):  [-179.84811]
Max Fidelity:  0.368111


termination reason: dfid
optimization timestamp (start time): 2023-01-06 14:57:00
timestamp (end time): 2023-01-06 14:57:05
elapsed time: 0:00:05.849204
Time per epoch 

In [345]:
N =1
insert_idx = 1
new_in_state = new_initial_state(insert_idx-1, N, 
                                 initial_state, 
                                 angles_filename)
new_fin_state = new_final_state(insert_idx, N, final_state, 
                                 angles_filename)
       

Tensor("alphas:0", shape=(1, 1), dtype=complex64)
N 1
start_idx 1
[-1.89103484  0.65941674  0.         -3.13894176]
Tensor("alphas:0", shape=(1, 1), dtype=complex64)


In [346]:
#new_fin_state

In [347]:
np.abs(new_fin_state.overlap(new_in_state))**2

0.36492746524401204

In [348]:
 #only optimize new layer        
opt_params_ = opt_params.copy()
opt_params_['N_blocks'] = 1
opt_params_['N_multistart'] = 1
opt_params_['initial_states'] = [new_in_state]
opt_params_['target_states'] = [new_fin_state]
opt_params_['user_angles'] =np.asarray([0.0,0.0,0.0,np.pi])
opt = BatchOptimizer(**opt_params_)
opt.print_info()

Tensor("alphas:0", shape=(1, 1), dtype=complex64)
optimization_type: state transfer
N_multistart: 1
N_blocks: 1
term_fid: 0.999
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: [0.      0.      0.      3.14159]
N_cav: 5
filename: Fock 1.h5

Best circuit parameters found:
betas:         [0.+0.j]
alphas:        [0.+0.j]
phis (deg):    [0.]
thetas (deg):  [-180.]
Max Fidelity:  0.364928




In [349]:
opt.optimize()

Start time: 2023-01-06 14:57:35
 Epoch: 24 / 500 Max Fid: 0.367311 Avg Fid: 0.367311 Max dFid: 0.000001 Avg dFid: 0.000001 Elapsed time: 0:00:04.661946 Remaing time: 0:01:32.461925
 max dFid: 0.000001
dFid stop: 0.000001


 Optimization stopped.  No dfid is greater than dfid_stop

optimization_type: state transfer
N_multistart: 1
N_blocks: 1
term_fid: 0.999
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: [0.      0.      0.      3.14159]
N_cav: 5
filename: Fock 1.h5

Best circuit parameters found:
betas:         [-0.02012-0.15193j]
alphas:        [0.+0.j]
phis (deg):    [0.]
thetas (deg):  [-179.85347]
Max Fidelity:  0.367311


termination reason: dfid
optimization timestamp (start time): 2023-01-06 14:57:35
timestamp (end time): 2023-01-06 14:57:40
elapsed time: 0:00:04.664582
Time per epoch (epoch size = 10): 0:

'2023-01-06 14:57:35'

In [350]:
new_angles_filename = 'test1.txt'
opt.save_angles(new_angles_filename)

In [351]:
opt.save_angles(new_angles_filename)
#update angles
angles_filename = insert_angles(insert_idx,
                                angles_filename,
                                new_angles_filename)
print('Now angles are ')
print(np.loadtxt(angles_filename))

Now angles are 
[[-1.89103484 -0.02012439]
 [ 0.65941674 -0.15192528]
 [ 0.          0.        ]
 [-3.13894176 -3.13903546]]


In [196]:
# a = [[2,3], [3,4]]
# b = [[3,6], [6,8]]
# np.concatenate((a,b),axis=1)

array([[2, 3, 3, 6],
       [3, 4, 6, 8]])

In [197]:
# a[0] = np.concatenate((a[0], b[0])).tolist()
# a[1] = np.concatenate((a[1], b[1])).tolist()
# np.array(a)

array([[2, 3, 3, 6],
       [3, 4, 6, 8]])

In [198]:
# a = [1,2,3]
# b= (np.array(a))
# b.reshape((3,1))

array([[1],
       [2],
       [3]])

In [199]:
#b

array([1, 2, 3])

In [226]:
def insert_angles(insert_idx, old_angles_filename, new_angles_filename): 
    '''
    Insert angles of a new single layer into the old angles
    '''
    old_ang = np.loadtxt(old_angles_filename)
    num_types = len(old_ang) # types of angles like beta_real, beta_imag, phi, theta
    #reshape old angles 
    if len(old_ang.shape) == 1: 
        old_ang = old_ang.reshape((num_types,1))
    old_ang = old_ang.tolist()
    
    new_ang = (np.loadtxt(new_angles_filename).reshape((num_types,1))).tolist()
    
    for n in range(num_types): 
        if insert_idx == 0: 
            old_ang[n] = np.concatenate((new_ang[n], old_ang[n])).tolist()
        else: 
            old_ang[n] = np.concatenate((old_ang[n][:insert_idx], new_ang[n], old_ang[n][insert_idx:])).tolist()
    np.savetxt(old_angles_filename, old_ang)
    return old_angles_filename

In [242]:
main(psi_i, psi_t)

Start time: 2023-01-06 14:25:23
Tensor("alphas:0", shape=(1, 1), dtype=complex64)
 Epoch: 40 / 500 Max Fid: 0.368118 Avg Fid: 0.368118 Max dFid: 0.000001 Avg dFid: 0.000001 Elapsed time: 0:00:07.228292 Remaing time: 0:01:23.125355
 max dFid: 0.000001
dFid stop: 0.000001


 Optimization stopped.  No dfid is greater than dfid_stop

optimization_type: state transfer
N_multistart: 1
N_blocks: 1
term_fid: 0.999
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 5
filename: Fock 1.h5

Best circuit parameters found:
betas:         [0.5314-1.93093j]
alphas:        [0.+0.j]
phis (deg):    [0.]
thetas (deg):  [-179.84703]
Max Fidelity:  0.368118


termination reason: dfid
optimization timestamp (start time): 2023-01-06 14:25:23
timestamp (end time): 2023-01-06 14:25:31
elapsed time: 0:00:07.231037
Time per epoch (e

KeyboardInterrupt: 

In [ ]:
opt = BatchOptimizer(**opt_params)
opt.print_info()

In [84]:
opt.optimize()

Start time: 2023-01-05 10:01:33
 Epoch: 1 / 500 Max Fid: 0.368118 Avg Fid: 0.368113 Max dFid: -0.000001 Avg dFid: -0.000002 Elapsed time: 0:00:00.213723 Remaing time: 0:01:46.647630
 max dFid: -0.000001
dFid stop: 0.000001


 Optimization stopped.  No dfid is greater than dfid_stop

optimization_type: state transfer
N_multistart: 10
N_blocks: 1
term_fid: 0.999
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 5
filename: Fock 1.h5

Best circuit parameters found:
betas:         [0.53476+1.92957j]
alphas:        [0.+0.j]
phis (deg):    [0.]
thetas (deg):  [-179.96347]
Max Fidelity:  0.368119


termination reason: dfid
optimization timestamp (start time): 2023-01-05 10:01:33
timestamp (end time): 2023-01-05 10:01:33
elapsed time: 0:00:00.216714
Time per epoch (epoch size = 10): 0:00:00.216714
Time per Adam 

'2023-01-05 10:01:33'

In [85]:
opt.best_circuit()['betas']

array([0.53476286+1.9295701j], dtype=complex64)

In [86]:
angles_filename = 'test.txt'

In [87]:
opt.save_angles(angles_filename)

In [91]:
pulse_sim = ecd_pulse_single_mode(param_file = angles_filename) 

In [93]:
pulse_sim.betas

array([0.53476286+1.92957008j])

In [73]:
params = np.loadtxt(angles_filename)

In [76]:
params

array([ 0.53127664,  1.93096542,  0.        , -3.14159203])

In [74]:
len(params.shape)

1

In [75]:
type(params[0]) == np.ndarray

False

In [60]:
a = 2
b = np.array([a])
type(a) == np.ndarray

False

In [61]:
type(b) == np.ndarray

True

In [62]:
b

array([2])

# DUMP 

#### Filename for angles to be stored

In [50]:
def main(layers, fname = fname, df = df):
    '''
    Vary layers, get fidelity
    '''
    for layer in layers: 
        #optimizer
        opt_params['N_blocks'] = layer
        opt = BatchOptimizer(**opt_params)
        opt.optimize()
        BO_fid = opt.best_fidelity()
        angles_filename = 'test_opt_angles.txt'
        opt.save_angles(filename = angles_filename)
        
        #pulses
        pulse_sim = ecd_pulse_single_mode(param_file = angles_filename,
                                 kappa = 1/(2e+6)) 
        pulse_sim.get_pulses()
        
        pulse_time = len(pulse_sim.alpha)
        
        df_new = pd.DataFrame([[ pulse_time, layer, BO_fid]], columns=columns)
        if df is None : 
            df = df_new
        else:
            df = df.append(df_new, ignore_index = True)
        df.to_csv(fname, index=False)

In [54]:
layers = [i for i in range(2, 8, 1)]

In [55]:
layers

[2, 3, 4, 5, 6, 7]

In [56]:
main(layers)

None
Start time: 2022-10-21 09:54:25
Tensor("alphas:0", shape=(1, 10), dtype=complex64)
Tensor("alphas:0", shape=(2, 10), dtype=complex64)
 Epoch: 34 / 500 Max Fid: 0.367880 Avg Fid: 0.367880 Max dFid: 0.000001 Avg dFid: 0.000000 Elapsed time: 0:00:04.246430 Remaing time: 0:00:58.201066
 max dFid: 0.000001
dFid stop: 0.000001


 Optimization stopped.  No dfid is greater than dfid_stop

optimization_type: state transfer
N_multistart: 10
N_blocks: 2
term_fid: 0.995
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 15
filename: Fock 1.h5

Best circuit parameters found:
betas:         [-0.1928 -1.89285j -0.61323+0.06246j]
alphas:        [0.+0.j]
phis (deg):    [ 0.      69.50025]
thetas (deg):  [71.78806 71.78809]
Max Fidelity:  0.367880


termination reason: dfid
optimization timestamp (start time): 2022-10

/home/eag190/miniconda3/envs/simulations/lib/python3.9/site-packages/scipy/signal/_peak_finding.py:261: ComplexWarning: Casting complex values to real discards the imaginary part
  value = np.asarray(value, order='C', dtype=np.float64)


---------------------------
Final Displacement: 0.8082848796100593
Modified conditional displacement called
---------------------------
Final Displacement: 9.664088599323192e-05
None
Start time: 2022-10-21 09:54:48
Tensor("alphas:0", shape=(1, 10), dtype=complex64)
Tensor("alphas:0", shape=(4, 10), dtype=complex64)


/tmp/ipykernel_30326/2741616155.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df_new, ignore_index = True)


 Epoch: 65 / 500 Max Fid: 0.981403 Avg Fid: 0.888826 Max dFid: 0.000001 Avg dFid: 0.000000 Elapsed time: 0:00:08.769133 Remaing time: 0:00:58.685735
 max dFid: 0.000001
dFid stop: 0.000001


 Optimization stopped.  No dfid is greater than dfid_stop

optimization_type: state transfer
N_multistart: 10
N_blocks: 4
term_fid: 0.995
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 15
filename: Fock 1.h5

Best circuit parameters found:
betas:         [-1.56612+0.03763j  0.02434+1.0128j  -0.65398+0.01572j -0.     +0.j     ]
alphas:        [0.+0.j]
phis (deg):    [  0.      -89.99999  89.99978   0.00022]
thetas (deg):  [ 90.00008 -89.99989  89.99982  89.99994]
Max Fidelity:  0.981402


termination reason: dfid
optimization timestamp (start time): 2022-10-21 09:54:48
timestamp (end time): 2022-10-21 09:54:57
elap

/home/eag190/miniconda3/envs/simulations/lib/python3.9/site-packages/scipy/signal/_peak_finding.py:261: ComplexWarning: Casting complex values to real discards the imaginary part
  value = np.asarray(value, order='C', dtype=np.float64)


---------------------------
Final Displacement: 1.0130914793872088
Modified conditional displacement called
---------------------------
Final Displacement: 0.6541738038392164
Modified conditional displacement called
---------------------------
Final Displacement: 1.5540200180484895e-06
None
Start time: 2022-10-21 09:54:59
Tensor("alphas:0", shape=(1, 10), dtype=complex64)
Tensor("alphas:0", shape=(5, 10), dtype=complex64)


/tmp/ipykernel_30326/2741616155.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df_new, ignore_index = True)


 Epoch: 30 / 500 Max Fid: 0.996476 Avg Fid: 0.893581 Max dFid: 0.005137 Avg dFid: 0.001107 Elapsed time: 0:00:04.608124 Remaing time: 0:01:12.193950

 Optimization stopped. Term fidelity reached.

optimization_type: state transfer
N_multistart: 10
N_blocks: 5
term_fid: 0.995
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 15
filename: Fock 1.h5

Best circuit parameters found:
betas:         [ 1.11966-1.10192j -0.67489-1.01431j  0.13101-0.65519j  0.66285-1.00006j
  0.12103-0.1409j ]
alphas:        [0.+0.j]
phis (deg):    [  0.       92.63541  62.54083 -72.75242 156.13202]
thetas (deg):  [ 89.90002  87.85105 -67.17851 -41.87074  77.73803]
Max Fidelity:  0.996551


termination reason: term_fid
optimization timestamp (start time): 2022-10-21 09:54:59
timestamp (end time): 2022-10-21 09:55:04
elapsed time: 

/home/eag190/miniconda3/envs/simulations/lib/python3.9/site-packages/scipy/signal/_peak_finding.py:261: ComplexWarning: Casting complex values to real discards the imaginary part
  value = np.asarray(value, order='C', dtype=np.float64)


---------------------------
Final Displacement: 1.2191270047078664
Modified conditional displacement called
---------------------------
Final Displacement: 0.6681571388245261
Modified conditional displacement called
---------------------------
Final Displacement: 1.199792577038323
Modified conditional displacement called
---------------------------
Final Displacement: 0.1857302894452685
None
Start time: 2022-10-21 09:55:06
Tensor("alphas:0", shape=(1, 10), dtype=complex64)
Tensor("alphas:0", shape=(6, 10), dtype=complex64)
 Epoch: 0 / 500 Max Fid: 0.190119 Avg Fid: 0.082922 Max dFid: 0.000000 Avg dFid: 0.000000 Elapsed time: 0:00:00.147046 Remaing time: 0:00:00

/tmp/ipykernel_30326/2741616155.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df_new, ignore_index = True)


 Epoch: 22 / 500 Max Fid: 0.995332 Avg Fid: 0.927133 Max dFid: 0.079114 Avg dFid: 0.013628 Elapsed time: 0:00:03.837784 Remaing time: 0:01:23.384586

 Optimization stopped. Term fidelity reached.

optimization_type: state transfer
N_multistart: 10
N_blocks: 6
term_fid: 0.995
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 15
filename: Fock 1.h5

Best circuit parameters found:
betas:         [ 0.21338-0.9227j  -0.40312+0.25766j -0.63347-0.64369j  0.65627-0.47364j
 -0.2451 -0.38495j  0.00481+0.76952j]
alphas:        [0.+0.j]
phis (deg):    [   0.       -27.78805  113.75288 -102.28375 -117.25365   39.13402]
thetas (deg):  [-126.23036   64.22308  -82.9809   -89.88346 -104.91428 -115.89619]
Max Fidelity:  0.995384


termination reason: term_fid
optimization timestamp (start time): 2022-10-21 09:55:06
timest

/home/eag190/miniconda3/envs/simulations/lib/python3.9/site-packages/scipy/signal/_peak_finding.py:261: ComplexWarning: Casting complex values to real discards the imaginary part
  value = np.asarray(value, order='C', dtype=np.float64)


---------------------------
Final Displacement: 0.47843052805310526
Modified conditional displacement called
---------------------------
Final Displacement: 0.9031128035875121
Modified conditional displacement called
---------------------------
Final Displacement: 0.8093351411648341
Modified conditional displacement called
---------------------------
Final Displacement: 0.4563545542156136
Modified conditional displacement called
---------------------------
Final Displacement: 0.7695352845311457
None
Start time: 2022-10-21 09:55:14
Tensor("alphas:0", shape=(1, 10), dtype=complex64)
Tensor("alphas:0", shape=(7, 10), dtype=complex64)
 Epoch: 0 / 500 Max Fid: 0.197437 Avg Fid: 0.064379 Max dFid: 0.000000 Avg dFid: 0.000000 Elapsed time: 0:00:00.144243 Remaing time: 0:00:00

/tmp/ipykernel_30326/2741616155.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df_new, ignore_index = True)


 Epoch: 10 / 500 Max Fid: 0.998352 Avg Fid: 0.928494 Max dFid: 0.084496 Avg dFid: 0.030891 Elapsed time: 0:00:02.081944 Remaing time: 0:01:42.015267

 Optimization stopped. Term fidelity reached.

optimization_type: state transfer
N_multistart: 10
N_blocks: 7
term_fid: 0.995
dfid_stop: 1e-06
no_CD_end: False
learning_rate: 0.01
epoch_size: 10
epochs: 500
beta_scale: 3.0
alpha_scale: 1.0
theta_scale: 3.141592653589793
use_displacements: False
use_phase: False
name: Fock 1
comment: 
user_angles: None
N_cav: 15
filename: Fock 1.h5

Best circuit parameters found:
betas:         [ 0.92991+1.11229j  0.62484-0.42947j  0.02075+0.75208j -0.75133-0.07144j
  0.97904-1.62472j  1.41153-1.63676j  0.01175-0.11535j]
alphas:        [0.+0.j]
phis (deg):    [  0.       88.63784 103.48551  66.79702 -46.19493  38.19178  34.0309 ]
thetas (deg):  [  90.9986   123.20777   82.30898 -103.57394  -36.25889    1.13154
  -76.63657]
Max Fidelity:  0.998343


termination reason: term_fid
optimization timestamp (start

/home/eag190/miniconda3/envs/simulations/lib/python3.9/site-packages/scipy/signal/_peak_finding.py:261: ComplexWarning: Casting complex values to real discards the imaginary part
  value = np.asarray(value, order='C', dtype=np.float64)


---------------------------
Final Displacement: 0.7585273185220985
Modified conditional displacement called
---------------------------
Final Displacement: 0.7523709177577791
Modified conditional displacement called
---------------------------
Final Displacement: 0.7547185338970385
Modified conditional displacement called
---------------------------
Final Displacement: 1.8968997240866923
Modified conditional displacement called
---------------------------
Final Displacement: 2.1613383379471034
Modified conditional displacement called
---------------------------
Final Displacement: 0.11594115952505771


/tmp/ipykernel_30326/2741616155.py:25: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df_new, ignore_index = True)
