# Imports 

In [1]:
print('hi')

hi


In [3]:
import sys
sys.path

['C:\\Users\\Eesh Gupta\\Documents\\RU Research\\Chakram\\Multimode-Conditional-Displacements\\hpc_runs\\multimode_circle_grape\\Tensorflow2_code_migration',
 'C:\\Users\\Eesh Gupta\\anaconda\\python38.zip',
 'C:\\Users\\Eesh Gupta\\anaconda\\DLLs',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda',
 '',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\qoc',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal-control',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\locket-0.2.1-py3.8.egg',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Eesh Gupta\\.ipython']

In [4]:
new_path= 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal-control2'
sys.path.append(new_path)

In [5]:
%matplotlib inline
import os
import sys
import inspect
import numpy as np
from scipy.special import factorial
import h5py

#data_path = '/data'     ... data path specified later
#data_path
#initial_pulse = '../pulses/example_pulses/transmon_cat_initial_pulse.h5'
from h5py import File
import matplotlib.pyplot as plt
from pylab import*
from qutip import*

from scipy import interpolate
font = {'family' : 'normal',
        'weight' : 'normal',
        'size'   : 18}

matplotlib.rc('font', **font)


In [6]:
from quantum_optimal_control.helper_functions.grape_functions import *
from quantum_optimal_control.main_grape.grape import Grape
from quantum_optimal_control import*

In [7]:
%load_ext autoreload
%autoreload 2

$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}
\newcommand{\bra}[1]{\left\langle{#1}\right|}$$

# 3DMM2 parameters

In [8]:
# chi = Peak splitting MHz
chis = 2*array([-33.1962, -0.8676]) 
kappas  = array([0,0]) # kHz

# Multimode circle grape

In [9]:
#TODO: Figure out why relative import doesn't work
from circle_grape_v3 import *

done


In [10]:
transmon_levels = 2

#  Params :  $\alpha = 30.0 , \delta_c = -0.030$ GHz, $\tau = 500$ ns, $\Omega_{max} =1$ MHz

In [39]:
mode = 0
mode_levels = 2
chi,kappa = chis[mode]*1e-6,kappas[mode]*1e-6
circle_grape_params = {"chis":[chi],"kappas":[kappa],"alpha":30.0,"delta_c":-0.01}

op = multimode_circle_grape_optimal_control(mode_state_num = mode_levels,
                                            number_of_modes = 1,hparams = circle_grape_params,add_disp_kerr=False)




In [40]:
import sys
sys.path

['C:\\Users\\Eesh Gupta\\Documents\\RU Research\\Chakram\\Multimode-Conditional-Displacements\\hpc_runs\\multimode_circle_grape\\Tensorflow2_code_migration',
 'C:\\Users\\Eesh Gupta\\anaconda\\python38.zip',
 'C:\\Users\\Eesh Gupta\\anaconda\\DLLs',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda',
 '',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\qoc',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal-control',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\locket-0.2.1-py3.8.egg',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Eesh Gupta\\.ipython',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal

In [41]:
data_path = ''#'/home/eag190/Multimode-Conditional-Displacements/hpc_runs/multimode_circle_grape/sample workflow/data'

In [42]:
tf.__version__

'2.7.0'

In [43]:
states_forbidden_list = []
total_time = 100.0
steps  = 50  #number of points over the total time where amplitudes will be specified

convergence = {'rate': 0.01, 'update_step': 10, 'max_iterations': 100,
               'conv_target': 3e-4, 'learning_rate_decay': 500.0}


reg_coeffs = {'dwdt': 0.1, 'd2wdt2': 1.0e-3, 'forbid_dressed': False,
               'states_forbidden_list':states_forbidden_list,
               'forbidden_coeff_list': [1.0*steps] * len(states_forbidden_list)}



initial_guess = None

ss = op.run_optimal_control(state_transfer = True, initial_states = [0], target_states = [1], 
                        total_time = total_time, steps = steps,max_amp = 1e-2, 
                        taylor_terms = None,is_dressed=False, 
                        convergence = convergence, reg_coeffs =  reg_coeffs,
                        plot_only_g = True,
                        states_forbidden_list = states_forbidden_list,initial_guess = initial_guess, 
                        file_name="g0_to_g1_circlgrape", data_path=data_path, save = True)

[2, 4, 2]
starting states:
[array([1., 0., 0., 0.])]
target states:
[array([0., 1., 0., 0.])]
[]
Hops are(2, 4, 4)
tensorflow2 grape
data saved at: 00165_g0_to_g1_circlgrape.h5
Using 5 Taylor terms and 0 Scaling & Squaring terms
Propagators initialized.
[array([0., 1., 0., 0., 0., 0., 0., 0.])]
Operators weight initialized.


c:\users\eesh gupta\documents\ru research\chakram\quantum-optimal-control\quantum_optimal_control\helper_functions\data_management.py:13: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  h5py.File.__init__(self, *args, **kwargs)


Vectors initialized.
inside inner product funtion
tf.Tensor(0.0, shape=(), dtype=float32)
inside inner product funtion
tf.Tensor(0.99999845, shape=(), dtype=float32)
Training loss initialized.
Not added train.saver functionality yet.
GPU Not available now; will integrate later
(2, 50)
no changing learning rate
inside tape
(2, 50)
inner_product
tf.Tensor(
[[ 0.9871374 ]
 [ 0.        ]
 [ 0.14804615]
 [ 0.        ]
 [-0.01942636]
 [ 0.        ]
 [-0.05713104]
 [ 0.        ]], shape=(8, 1), dtype=float32)
tf.Tensor(
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)
inside inner product funtion
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
inside inner product funtion
tf.Tensor(0.99999845, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
inside grad func
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-0.11426207],

inside grad func
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-0.12242632],
       [ 0.        ],
       [-0.03822443],
       [ 0.        ],
       [-0.2647103 ],
       [ 0.        ],
       [-1.9782509 ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.2647103 ],
       [ 0.        ],
       [-1.9782509 ],
       [ 0.        ],
       [-0.12242632],
       [ 0.        ],
       [ 0.03822443],
       [ 0.        ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-0.16451322],
       [ 0.        ],
       [-0.04127157],
       [ 0.        ],
       [-0.3037436 ],
       [ 0.        ],
       [-1.96951   ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 

[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.051987  ],
       [ 0.        ],
       [-0.00314064],
       [ 0.        ],
       [-0.04393565],
       [ 0.        ],
       [-1.9988385 ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.04393565],
       [ 0.        ],
       [-1.9988385 ],
       [ 0.        ],
       [ 0.051987  ],
       [ 0.        ],
       [ 0.00314064],
       [ 0.        ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.04126894],
       [ 0.        ],
       [-0.00354415],
       [ 0.        ],
       [-0.05038627],
       [ 0.        ],
       [-1.9989357 ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.05038627],
       [ 0.        ],
       [-1.9989357 ],
       [ 0.    

In [ ]:
op.controlHs()

In [46]:
1\2

SyntaxError: unexpected character after line continuation character (<ipython-input-46-7992d37700e4>, line 1)

In [47]:
hf = op.openfile()

In [60]:
mode = 0
mode_levels = 10
chi,kappa = chis[mode]*1e-3,kappas[mode]*1e-6
circle_grape_params = {"chis":[chi],"kappas":[kappa],"alpha":1.0,"delta_c":-0.0010}

op = multimode_circle_grape_optimal_control(mode_state_num = mode_levels,
                                            number_of_modes = 1,hparams = circle_grape_params,add_disp_kerr=False)


states_forbidden_list = []
total_time = 10.0
steps  = 5  #number of points over the total time where amplitudes will be specified

convergence = {'rate': 0.1, 'update_step': 10, 'max_iterations': 100,
               'conv_target': 3e-4, 'learning_rate_decay': 500.0}


reg_coeffs = {'dwdt': 0.1, 'd2wdt2': 1.0e-3, 'forbid_dressed': False,
               'states_forbidden_list':states_forbidden_list,
               'forbidden_coeff_list': [1.0*steps] * len(states_forbidden_list)}



initial_guess = None
# initial_guess = np.ones((2, int(steps))) * 2*np.pi * 10.0e-6/np.sqrt(2)
# initial_guess = np.random.normal(loc=0.0, scale=2*np.pi*15e-7, size=(len(Hops), int(steps)))


# expt_name = 'g0_to_g2_blockade'
# file_number = 29
# initial_pulse = "S:/_Data/191018 - Picollo cavity cooldown 15 real\\optimal control pulses\\blockade_pulses\\" + \
#                 str(file_number).zfill(5) + "_" + expt_name.lower()+".h5"

# with h5py.File(initial_pulse,'r') as hf:
#     last_u0 = np.array(hf['uks'])[-1]
# initial_guess = last_u0


op.run_optimal_control(state_transfer = True, initial_states = [0], target_states = [1], 
                        total_time = total_time, steps = steps,max_amp = 1e-3, 
                        taylor_terms = None,is_dressed=False, 
                        convergence = convergence, reg_coeffs =  reg_coeffs,
                        plot_only_g = True,
                        states_forbidden_list = states_forbidden_list,initial_guess = initial_guess, 
                        file_name="g0_to_g1_circlgrape", data_path=data_path)

[autoreload of quantum_optimal_control.core.run_session failed: Traceback (most recent call last):
  File "C:\Users\Eesh Gupta\anaconda\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\Eesh Gupta\anaconda\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Users\Eesh Gupta\anaconda\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\Eesh Gupta\anaconda\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\e

[2, 4, 2]
starting states:
[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])]
target states:
[array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])]
[]
Hops are(2, 20, 20)
tensorflow2 grape
data saved at: 00135_g0_to_g1_circlgrape.h5
Using 10 Taylor terms and 0 Scaling & Squaring terms
Propagators initialized.
Operators weight initialized.
Vectors initialized.
Training loss initialized.
Not added train.saver functionality yet.
GPU Not available now; will integrate later
(2, 5)
no changing learning rate
inside tape
(2, 5)
inner_product
tf.Tensor(
[[ 9.9997252e-01]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 5.5210474e-03]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 

(<tf.Variable 'Variable:0' shape=(2, 5) dtype=float32, numpy=
 array([[ 7.0815266e-05, -2.0475155e-03,  5.0403741e-03,  2.0882036e-03,
         -2.6779042e-03],
        [ 3.0881379e-04,  1.1925041e-03,  2.7112127e-03, -2.6543057e-03,
         -4.3190857e-03]], dtype=float32)>,
 [],
 '00135_g0_to_g1_circlgrape.h5')

In [59]:
hf['error'][-1]

[autoreload of quantum_optimal_control.core.run_session failed: Traceback (most recent call last):
  File "C:\Users\Eesh Gupta\anaconda\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\Eesh Gupta\anaconda\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Users\Eesh Gupta\anaconda\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\Eesh Gupta\anaconda\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\e

1.0

In [ ]:
op.plot_pulses()

In [ ]:
ss

In [ ]:
len(ss[0][0])

In [ ]:
op.fidelity()

In [ ]:
import os 
data_path = '/home/eag190/Multimode-Conditional-Displacements/hpc_runs/multimode_circle_grape/sample workflow/data'
file_path = 'test.h5'
file_path_f = os.path.join(data_path, file_path)
file_path_f

In [ ]:
hf = h5py.File(file_path_f, 'w')


In [ ]:
get_dressed_info

In [ ]:
w_c, v_c, dressed_id = get_dressed_info(op.H_rot())

In [ ]:
w_c

In [ ]:
v_c

In [ ]:
dressed_id