# Imports 

In [1]:
print('hi')

hi


In [2]:
import sys
sys.path

['C:\\Users\\Eesh Gupta\\Documents\\RU Research\\Chakram\\Multimode-Conditional-Displacements\\hpc_runs\\multimode_circle_grape\\Tensorflow2_code_migration',
 'C:\\Users\\Eesh Gupta\\anaconda\\python38.zip',
 'C:\\Users\\Eesh Gupta\\anaconda\\DLLs',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda',
 '',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\qoc',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal-control',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\locket-0.2.1-py3.8.egg',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Eesh Gupta\\.ipython']

In [3]:
new_path= 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal-control2'
sys.path.append(new_path)

In [4]:
%matplotlib inline
import os
import sys
import inspect
import numpy as np
from scipy.special import factorial
import h5py

#data_path = '/data'     ... data path specified later
#data_path
#initial_pulse = '../pulses/example_pulses/transmon_cat_initial_pulse.h5'
from h5py import File
import matplotlib.pyplot as plt
from pylab import*
from qutip import*

from scipy import interpolate
font = {'family' : 'normal',
        'weight' : 'normal',
        'size'   : 18}

matplotlib.rc('font', **font)


In [6]:
from quantum_optimal_control.helper_functions.grape_functions import *
from quantum_optimal_control.main_grape.grape import Grape
from quantum_optimal_control import*

In [7]:
%load_ext autoreload
%autoreload 2

$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}
\newcommand{\bra}[1]{\left\langle{#1}\right|}$$

# 3DMM2 parameters

In [8]:
# chi = Peak splitting MHz
chis = 2*array([-33.1962, -0.8676]) 
kappas  = array([0,0]) # kHz

# Multimode circle grape

In [9]:
#TODO: Figure out why relative import doesn't work
from circle_grape_v3 import *

done


In [10]:
transmon_levels = 2

#  Params :  $\alpha = 30.0 , \delta_c = -0.030$ GHz, $\tau = 500$ ns, $\Omega_{max} =1$ MHz

In [11]:
mode = 0
mode_levels = 2
chi,kappa = chis[mode]*1e-6,kappas[mode]*1e-6
circle_grape_params = {"chis":[chi],"kappas":[kappa],"alpha":30.0,"delta_c":-0.01}

op = multimode_circle_grape_optimal_control(mode_state_num = mode_levels,
                                            number_of_modes = 1,hparams = circle_grape_params,add_disp_kerr=False)




In [12]:
import sys
sys.path

['C:\\Users\\Eesh Gupta\\Documents\\RU Research\\Chakram\\Multimode-Conditional-Displacements\\hpc_runs\\multimode_circle_grape\\Tensorflow2_code_migration',
 'C:\\Users\\Eesh Gupta\\anaconda\\python38.zip',
 'C:\\Users\\Eesh Gupta\\anaconda\\DLLs',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda',
 '',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\qoc',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal-control',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\locket-0.2.1-py3.8.egg',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Eesh Gupta\\.ipython',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal

In [13]:
data_path = ''#'/home/eag190/Multimode-Conditional-Displacements/hpc_runs/multimode_circle_grape/sample workflow/data'

In [14]:
tf.__version__

'2.7.0'

In [23]:
states_forbidden_list = []
total_time = 5000.0
steps  = 500  #number of points over the total time where amplitudes will be specified

convergence = {'rate': 0.01, 'update_step': 10, 'max_iterations': 100,
               'conv_target': 3e-4, 'learning_rate_decay': 500.0}


reg_coeffs = {'dwdt': 0.1, 'd2wdt2': 1.0e-3, 'forbid_dressed': False,
               'states_forbidden_list':states_forbidden_list,
               'forbidden_coeff_list': [1.0*steps] * len(states_forbidden_list)}



initial_guess = None

ss = op.run_optimal_control(state_transfer = True, initial_states = [0], target_states = [1], 
                        total_time = total_time, steps = steps,max_amp = 1e-2, 
                        taylor_terms = None,is_dressed=False, 
                        convergence = convergence, reg_coeffs =  reg_coeffs,
                        plot_only_g = True,
                        states_forbidden_list = states_forbidden_list,initial_guess = initial_guess, 
                        file_name="g0_to_g1_circlgrape", data_path=data_path, save = True)

[2, 4, 2]
starting states:
[array([1., 0., 0., 0.])]
target states:
[array([0., 1., 0., 0.])]
[]
Hops are(2, 4, 4)
tensorflow2 grape
data saved at: 00144_g0_to_g1_circlgrape.h5


c:\users\eesh gupta\documents\ru research\chakram\quantum-optimal-control\quantum_optimal_control\helper_functions\data_management.py:13: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  h5py.File.__init__(self, *args, **kwargs)


Using 11 Taylor terms and 0 Scaling & Squaring terms
Propagators initialized.
Operators weight initialized.
Vectors initialized.
Training loss initialized.
Not added train.saver functionality yet.
GPU Not available now; will integrate later
(2, 500)
no changing learning rate
inside tape
(2, 500)
inner_product
tf.Tensor(
[[ 0.5359605 ]
 [ 0.        ]
 [ 0.47933024]
 [ 0.        ]
 [ 0.4519175 ]
 [ 0.        ]
 [-0.52797633]
 [ 0.        ]], shape=(8, 1), dtype=float32)
tf.Tensor(
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(8, 1), dtype=float32)
tf.Tensor([[0.]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.]], shape=(1, 1), dtype=float32)
inside grad func
tf.Tensor(
[[-0.]
 [-1.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-5.279763 ],
       [ 0.       ],
       [ 4.519175 ],
       [ 0.       ],
       [-4.7933025],
       [ 0.       ],
       [-5.359605 ],
       [ 0.       ]], dtype=floa

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.31347576]
 [ 0.        ]
 [-0.15450627]
 [ 0.        ]
 [-0.935546  ]
 [ 0.        ]
 [-0.05113047]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-5.5684843],
       [ 0.       ],
       [ 4.4469795],
       [ 0.       ],
       [-5.72775  ],
       [ 0.       ],
       [-4.050824 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 5.72775  ],
       [ 0.       ],
       [-4.050824 ],
       [ 0.       ],
       [-5.5684843],
       [ 0.       ],
       [-4.4469795],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.8125924 ]
 [ 0.        ]
 [-0.10309447]
 [ 0.        ]
 [-0.56503093]
 [ 0.        ]
 [ 0.09901999]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-5.9173136],
       [ 0.       ],
       [ 3.9728584],
       [ 0.       ],
    

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.35143968]
 [ 0.        ]
 [-0.23116513]
 [ 0.        ]
 [-0.9015732 ]
 [ 0.        ]
 [ 0.10108402]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-6.5514464],
       [ 0.       ],
       [ 2.9772506],
       [ 0.       ],
       [-5.68986  ],
       [ 0.       ],
       [-3.9799495],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 5.68986  ],
       [ 0.       ],
       [-3.9799495],
       [ 0.       ],
       [-6.5514464],
       [ 0.       ],
       [-2.9772506],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.8197765 ]
 [ 0.        ]
 [-0.11287674]
 [ 0.        ]
 [-0.52342975]
 [ 0.        ]
 [ 0.20309131]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-6.481744 ],
       [ 0.       ],
       [ 3.0627143],
       [ 0.       ],
    

inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.38296017]
 [ 0.        ]
 [ 0.23103982]
 [ 0.        ]
 [ 0.8693264 ]
 [ 0.        ]
 [-0.21031533]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.0100474],
       [ 0.       ],
       [ 1.9990585],
       [ 0.       ],
       [-5.3409953],
       [ 0.       ],
       [-4.282141 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 5.3409953],
       [ 0.       ],
       [-4.282141 ],
       [ 0.       ],
       [-7.0100474],
       [ 0.       ],
       [-1.9990585],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.82100326]
 [ 0.        ]
 [ 0.07692992]
 [ 0.        ]
 [ 0.48301575]
 [ 0.        ]
 [-0.29449943]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-6.9587207],
       [ 0.       ],
       [ 2.1431315],
       [ 0.       ],
    

tf.Tensor(
[[ 0.        ]
 [-0.8158461 ]
 [ 0.        ]
 [-0.05437961]
 [ 0.        ]
 [-0.44412068]
 [ 0.        ]
 [ 0.3663249 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.2906437],
       [ 0.       ],
       [ 1.3889898],
       [ 0.       ],
       [-5.254536 ],
       [ 0.       ],
       [-4.160179 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 5.254536 ],
       [ 0.       ],
       [-4.160179 ],
       [ 0.       ],
       [-7.2906437],
       [ 0.       ],
       [-1.3889898],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.92353773]
 [ 0.        ]
 [ 0.15372857]
 [ 0.        ]
 [ 0.11472111]
 [ 0.        ]
 [ 0.33209002]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.269286 ],
       [ 0.       ],
       [ 1.5186685],
       [ 0.       ],
       [-5.334267 ],


inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.80576813]
 [ 0.        ]
 [ 0.1838422 ]
 [ 0.        ]
 [ 0.10137615]
 [ 0.        ]
 [ 0.5537703 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.0474939e+00],
       [ 0.0000000e+00],
       [ 5.5963178e-03],
       [ 0.0000000e+00],
       [-5.5144558e+00],
       [ 0.0000000e+00],
       [-2.1974142e+00],
       [ 0.0000000e+00]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 5.5144558e+00],
       [ 0.0000000e+00],
       [-2.1974142e+00],
       [ 0.0000000e+00],
       [-8.0474939e+00],
       [ 0.0000000e+00],
       [-5.5963178e-03],
       [ 0.0000000e+00]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.58893126]
 [ 0.        ]
 [ 0.47897848]
 [ 0.        ]
 [ 0.5485854 ]
 [ 0.        ]
 [ 0.3504177 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.075979  ],
  

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.00345   ]
 [ 0.        ]
 [ 0.58745176]
 [ 0.        ]
 [ 0.79776096]
 [ 0.        ]
 [-0.13588303]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.7491674],
       [ 0.       ],
       [-1.5215557],
       [ 0.       ],
       [-5.1327157],
       [ 0.       ],
       [-3.360145 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 5.1327157],
       [ 0.       ],
       [-3.360145 ],
       [ 0.       ],
       [-7.7491674],
       [ 0.       ],
       [ 1.5215557],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.       ]
 [ 0.4719618]
 [ 0.       ]
 [ 0.3915756]
 [ 0.       ]
 [ 0.6075174]
 [ 0.       ]
 [-0.5048182]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.764035 ],
       [ 0.       ],
       [-2.1130297],
       [ 0.       ],
       [-4.8

[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.509845 ],
       [ 0.       ],
       [-1.8688645],
       [ 0.       ],
       [-4.686    ],
       [ 0.       ],
       [-1.459924 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.686    ],
       [ 0.       ],
       [-1.459924 ],
       [ 0.       ],
       [-8.509845 ],
       [ 0.       ],
       [ 1.8688645],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.6590746 ]
 [ 0.        ]
 [ 0.31510445]
 [ 0.        ]
 [ 0.13530077]
 [ 0.        ]
 [ 0.669344  ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.494308 ],
       [ 0.       ],
       [-1.9752746],
       [ 0.       ],
       [-4.663842 ],
       [ 0.       ],
       [-1.481113 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.663842 ],
       [ 0. 

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.38081214]
 [ 0.        ]
 [-0.46657208]
 [ 0.        ]
 [-0.69192934]
 [ 0.        ]
 [ 0.39815173]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.277156  ],
       [ 0.        ],
       [-0.62034374],
       [ 0.        ],
       [-4.974149  ],
       [ 0.        ],
       [-2.522266  ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.974149  ],
       [ 0.        ],
       [-2.522266  ],
       [ 0.        ],
       [-8.277156  ],
       [ 0.        ],
       [ 0.62034374],
       [ 0.        ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.71069205]
 [ 0.        ]
 [-0.1520629 ]
 [ 0.        ]
 [-0.33962294]
 [ 0.        ]
 [ 0.59703285]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.295496 ],
       [ 0.       ],
       [-0.5745033],
       [ 

tf.Tensor(
[[ 0.        ]
 [-0.45050687]
 [ 0.        ]
 [-0.38004616]
 [ 0.        ]
 [-0.72401804]
 [ 0.        ]
 [ 0.35833675]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.905166  ],
       [ 0.        ],
       [-0.24500458],
       [ 0.        ],
       [-4.9395804 ],
       [ 0.        ],
       [-3.6123397 ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.9395804 ],
       [ 0.        ],
       [-3.6123397 ],
       [ 0.        ],
       [-7.905166  ],
       [ 0.        ],
       [ 0.24500458],
       [ 0.        ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.7710435 ]
 [ 0.        ]
 [-0.07371774]
 [ 0.        ]
 [-0.29096335]
 [ 0.        ]
 [ 0.561602  ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.03404   ],
       [ 0.        ],
       [-0.83296967],
       [ 0.        ],
 

inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.5154474 ]
 [ 0.        ]
 [-0.52784026]
 [ 0.        ]
 [-0.58811516]
 [ 0.        ]
 [-0.3313877 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.360994 ],
       [ 0.       ],
       [-0.7147717],
       [ 0.       ],
       [-4.8215456],
       [ 0.       ],
       [-2.517076 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.8215456],
       [ 0.       ],
       [-2.517076 ],
       [ 0.       ],
       [-8.360994 ],
       [ 0.       ],
       [ 0.7147717],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.06770361]
 [ 0.        ]
 [-0.6329866 ]
 [ 0.        ]
 [-0.7698962 ]
 [ 0.        ]
 [ 0.04475071]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.391109 ],
       [ 0.       ],
       [-0.8270747],
       [ 0.       ],
    

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.01038504]
 [ 0.        ]
 [-0.7146045 ]
 [ 0.        ]
 [-0.6944433 ]
 [ 0.        ]
 [ 0.08354693]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.426892 ],
       [ 0.       ],
       [-2.1133447],
       [ 0.       ],
       [-4.557876 ],
       [ 0.       ],
       [-1.9357507],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.557876 ],
       [ 0.       ],
       [-1.9357507],
       [ 0.       ],
       [-8.426892 ],
       [ 0.       ],
       [ 2.1133447],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.39849526]
 [ 0.        ]
 [-0.5475714 ]
 [ 0.        ]
 [-0.55143577]
 [ 0.        ]
 [ 0.4871188 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-8.497738 ],
       [ 0.       ],
       [-2.0785937],
       [ 0.       ],
    

[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.7812934],
       [ 0.       ],
       [-2.1753423],
       [ 0.       ],
       [-4.4630485],
       [ 0.       ],
       [-3.847166 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.4630485],
       [ 0.       ],
       [-3.847166 ],
       [ 0.       ],
       [-7.7812934],
       [ 0.       ],
       [ 2.1753423],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.12697275]
 [ 0.        ]
 [-0.5431652 ]
 [ 0.        ]
 [-0.81204766]
 [ 0.        ]
 [ 0.17154245]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.543373 ],
       [ 0.       ],
       [-2.201867 ],
       [ 0.       ],
       [-4.441208 ],
       [ 0.       ],
       [-4.3040795],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.441208 ],
       [ 0. 

[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.1295986],
       [ 0.       ],
       [-3.2654076],
       [ 0.       ],
       [-3.9304047],
       [ 0.       ],
       [-4.8018675],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 3.9304047],
       [ 0.       ],
       [-4.8018675],
       [ 0.       ],
       [-7.1295986],
       [ 0.       ],
       [ 3.2654076],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.       ]
 [ 0.292907 ]
 [ 0.       ]
 [-0.5843216]
 [ 0.       ]
 [-0.7449234]
 [ 0.       ]
 [-0.1336476]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-7.332547 ],
       [ 0.       ],
       [-3.08589  ],
       [ 0.       ],
       [-4.0343394],
       [ 0.       ],
       [-4.5205326],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.0343394],
       [ 0.       ],

tf.Tensor(
[[ 0.        ]
 [ 0.83873147]
 [ 0.        ]
 [-0.13331847]
 [ 0.        ]
 [-0.03382142]
 [ 0.        ]
 [-0.5268877 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-6.544457 ],
       [ 0.       ],
       [-3.4739285],
       [ 0.       ],
       [-3.7673788],
       [ 0.       ],
       [-5.559569 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 3.7673788],
       [ 0.       ],
       [-5.559569 ],
       [ 0.       ],
       [-6.544457 ],
       [ 0.       ],
       [ 3.4739285],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.6592852 ]
 [ 0.        ]
 [-0.41555008]
 [ 0.        ]
 [-0.5314548 ]
 [ 0.        ]
 [-0.33198753]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-6.4154987],
       [ 0.       ],
       [-3.4807224],
       [ 0.       ],
       [-3.7648103],


tf.Tensor(
[[ 0.        ]
 [-0.21903515]
 [ 0.        ]
 [ 0.30833256]
 [ 0.        ]
 [ 0.9222425 ]
 [ 0.        ]
 [ 0.08013872]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-5.062583 ],
       [ 0.       ],
       [-2.1702573],
       [ 0.       ],
       [-5.2447596],
       [ 0.       ],
       [-6.492519 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 5.2447596],
       [ 0.       ],
       [-6.492519 ],
       [ 0.       ],
       [-5.062583 ],
       [ 0.       ],
       [ 2.1702573],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.38200742]
 [ 0.        ]
 [ 0.28117606]
 [ 0.        ]
 [ 0.8635104 ]
 [ 0.        ]
 [-0.17134495]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-4.9746222],
       [ 0.       ],
       [-2.5122166],
       [ 0.       ],
       [-4.8277574],


inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.8848923 ]
 [ 0.        ]
 [ 0.05107535]
 [ 0.        ]
 [-0.45873222]
 [ 0.        ]
 [ 0.06260923]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-2.5722833],
       [ 0.       ],
       [-1.2054665],
       [ 0.       ],
       [-5.0723877],
       [ 0.       ],
       [-8.136408 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 5.0723877],
       [ 0.       ],
       [-8.136408 ],
       [ 0.       ],
       [-2.5722833],
       [ 0.       ],
       [ 1.2054665],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.9817173 ]
 [ 0.        ]
 [ 0.10069741]
 [ 0.        ]
 [ 0.14614083]
 [ 0.        ]
 [ 0.06879032]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-2.9661665],
       [ 0.       ],
       [-1.5024815],
       [ 0.       ],
    

inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.1422907 ]
 [ 0.        ]
 [-0.11399555]
 [ 0.        ]
 [-0.9799079 ]
 [ 0.        ]
 [ 0.08084949]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-3.0526152],
       [ 0.       ],
       [-1.652535 ],
       [ 0.       ],
       [-4.778232 ],
       [ 0.       ],
       [-8.069647 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.778232 ],
       [ 0.       ],
       [-8.069647 ],
       [ 0.       ],
       [-3.0526152],
       [ 0.       ],
       [ 1.652535 ],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.46530402]
 [ 0.        ]
 [-0.01833098]
 [ 0.        ]
 [-0.87503314]
 [ 0.        ]
 [ 0.13217801]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-2.8395166],
       [ 0.       ],
       [-1.5760993],
       [ 0.       ],
    

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.09886182]
 [ 0.        ]
 [-0.09182495]
 [ 0.        ]
 [ 0.97925836]
 [ 0.        ]
 [-0.15114574]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-1.1552091],
       [ 0.       ],
       [-0.73734  ],
       [ 0.       ],
       [-4.666712 ],
       [ 0.       ],
       [-8.737485 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.666712 ],
       [ 0.       ],
       [-8.737485 ],
       [ 0.       ],
       [-1.1552091],
       [ 0.       ],
       [ 0.73734  ],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.50181115]
 [ 0.        ]
 [-0.13828284]
 [ 0.        ]
 [ 0.8529221 ]
 [ 0.        ]
 [-0.03980899]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-1.243354 ],
       [ 0.       ],
       [-0.7258793],
       [ 0.       ],
    

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.63197124]
 [ 0.        ]
 [ 0.02506261]
 [ 0.        ]
 [ 0.7313817 ]
 [ 0.        ]
 [-0.2550733 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-0.7121397],
       [ 0.       ],
       [-0.5625452],
       [ 0.       ],
       [-4.112694 ],
       [ 0.       ],
       [-9.069851 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 4.112694 ],
       [ 0.       ],
       [-9.069851 ],
       [ 0.       ],
       [-0.7121397],
       [ 0.       ],
       [ 0.5625452],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.08592772]
 [ 0.        ]
 [-0.11366405]
 [ 0.        ]
 [ 0.9609994 ]
 [ 0.        ]
 [-0.23701108]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-0.8364829],
       [ 0.       ],
       [-0.6359878],
       [ 0.       ],
    

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.8800193 ]
 [ 0.        ]
 [ 0.44055924]
 [ 0.        ]
 [ 0.12010943]
 [ 0.        ]
 [-0.1305572 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-1.7890568],
       [ 0.       ],
       [-0.8841092],
       [ 0.       ],
       [-1.4050096],
       [ 0.       ],
       [-9.697611 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 1.4050096],
       [ 0.       ],
       [-9.697611 ],
       [ 0.       ],
       [-1.7890568],
       [ 0.       ],
       [ 0.8841092],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.63613445]
 [ 0.        ]
 [ 0.32102233]
 [ 0.        ]
 [ 0.59246993]
 [ 0.        ]
 [-0.375839  ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-1.9664472 ],
       [ 0.        ],
       [-0.9913248 ],
       [ 0.        ],


inside grad func
tf.Tensor(
[[ 0.0000000e+00]
 [ 1.3070484e-01]
 [ 0.0000000e+00]
 [ 2.8290542e-05]
 [ 0.0000000e+00]
 [-8.8962376e-01]
 [ 0.0000000e+00]
 [ 4.3758950e-01]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-1.609963 ],
       [ 0.       ],
       [-0.8351983],
       [ 0.       ],
       [-1.7004476],
       [ 0.       ],
       [-9.68602  ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 1.7004476],
       [ 0.       ],
       [-9.68602  ],
       [ 0.       ],
       [-1.609963 ],
       [ 0.       ],
       [ 0.8351983],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.41486356]
 [ 0.        ]
 [ 0.2677213 ]
 [ 0.        ]
 [-0.7885391 ]
 [ 0.        ]
 [ 0.36663124]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-1.5528145],
       [ 0.       ],
       [-0.8564514],
 

[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-1.8622667 ],
       [ 0.        ],
       [-0.89418346],
       [ 0.        ],
       [-1.3542403 ],
       [ 0.        ],
       [-9.690122  ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 1.3542403 ],
       [ 0.        ],
       [-9.690122  ],
       [ 0.        ],
       [-1.8622667 ],
       [ 0.        ],
       [ 0.89418346],
       [ 0.        ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.13907799]
 [ 0.        ]
 [-0.05450466]
 [ 0.        ]
 [-0.8809705 ]
 [ 0.        ]
 [ 0.44897315]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-2.0567055],
       [ 0.       ],
       [-0.8983713],
       [ 0.       ],
       [-1.4481866],
       [ 0.       ],
       [-9.636684 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 1.448186

inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.9021147 ]
 [ 0.        ]
 [-0.32385972]
 [ 0.        ]
 [-0.23553206]
 [ 0.        ]
 [ 0.16071232]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-0.9117582],
       [ 0.       ],
       [-0.6579745],
       [ 0.       ],
       [-2.6856737],
       [ 0.       ],
       [-9.566764 ],
       [ 0.       ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 2.6856737],
       [ 0.       ],
       [-9.566764 ],
       [ 0.       ],
       [-0.9117582],
       [ 0.       ],
       [ 0.6579745],
       [ 0.       ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [ 0.6094259 ]
 [ 0.        ]
 [-0.18457496]
 [ 0.        ]
 [-0.7215638 ]
 [ 0.        ]
 [ 0.2718045 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-1.3752944],
       [ 0.       ],
       [-0.7565754],
       [ 0.       ],
    

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.5837174 ]
 [ 0.        ]
 [ 0.06493407]
 [ 0.        ]
 [ 0.75329375]
 [ 0.        ]
 [-0.29598346]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-0.3927281 ],
       [ 0.        ],
       [-0.20484108],
       [ 0.        ],
       [-3.5165153 ],
       [ 0.        ],
       [-9.350826  ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 3.5165153 ],
       [ 0.        ],
       [-9.350826  ],
       [ 0.        ],
       [-0.3927281 ],
       [ 0.        ],
       [ 0.20484108],
       [ 0.        ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.02865177]
 [ 0.        ]
 [-0.10343683]
 [ 0.        ]
 [ 0.96594584]
 [ 0.        ]
 [-0.2354334 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[-0.5863122 ],
       [ 0.        ],
       [-0.25715083],
      

[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.42177433],
       [ 0.        ],
       [-0.13856442],
       [ 0.        ],
       [-2.398547  ],
       [ 0.        ],
       [-9.697933  ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 2.398547  ],
       [ 0.        ],
       [-9.697933  ],
       [ 0.        ],
       [ 0.42177433],
       [ 0.        ],
       [ 0.13856442],
       [ 0.        ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.51943934]
 [ 0.        ]
 [ 0.08876905]
 [ 0.        ]
 [ 0.73604596]
 [ 0.        ]
 [-0.42489865]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.3870384 ],
       [ 0.        ],
       [-0.14555778],
       [ 0.        ],
       [-2.358112  ],
       [ 0.        ],
       [-9.709188  ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 

inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.7570146 ]
 [ 0.        ]
 [ 0.4486445 ]
 [ 0.        ]
 [ 0.28668088]
 [ 0.        ]
 [-0.3787634 ]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 1.0744257 ],
       [ 0.        ],
       [-0.06387141],
       [ 0.        ],
       [-0.70778954],
       [ 0.        ],
       [-9.916683  ],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.70778954],
       [ 0.        ],
       [-9.916683  ],
       [ 0.        ],
       [ 1.0744257 ],
       [ 0.        ],
       [ 0.06387141],
       [ 0.        ]], dtype=float32)>]
-----------------------------------
inside grad func
tf.Tensor(
[[ 0.        ]
 [-0.4494661 ]
 [ 0.        ]
 [ 0.16333506]
 [ 0.        ]
 [ 0.6607818 ]
 [ 0.        ]
 [-0.57850647]], shape=(8, 1), dtype=float32)
[<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[ 0.90422535],
       [ 0.        ],
       [-0.04997071],
      

In [ ]:
op.controlHs()

In [46]:
1\2

SyntaxError: unexpected character after line continuation character (<ipython-input-46-7992d37700e4>, line 1)

In [47]:
hf = op.openfile()

In [60]:
mode = 0
mode_levels = 10
chi,kappa = chis[mode]*1e-3,kappas[mode]*1e-6
circle_grape_params = {"chis":[chi],"kappas":[kappa],"alpha":1.0,"delta_c":-0.0010}

op = multimode_circle_grape_optimal_control(mode_state_num = mode_levels,
                                            number_of_modes = 1,hparams = circle_grape_params,add_disp_kerr=False)


states_forbidden_list = []
total_time = 10.0
steps  = 5  #number of points over the total time where amplitudes will be specified

convergence = {'rate': 0.1, 'update_step': 10, 'max_iterations': 100,
               'conv_target': 3e-4, 'learning_rate_decay': 500.0}


reg_coeffs = {'dwdt': 0.1, 'd2wdt2': 1.0e-3, 'forbid_dressed': False,
               'states_forbidden_list':states_forbidden_list,
               'forbidden_coeff_list': [1.0*steps] * len(states_forbidden_list)}



initial_guess = None
# initial_guess = np.ones((2, int(steps))) * 2*np.pi * 10.0e-6/np.sqrt(2)
# initial_guess = np.random.normal(loc=0.0, scale=2*np.pi*15e-7, size=(len(Hops), int(steps)))


# expt_name = 'g0_to_g2_blockade'
# file_number = 29
# initial_pulse = "S:/_Data/191018 - Picollo cavity cooldown 15 real\\optimal control pulses\\blockade_pulses\\" + \
#                 str(file_number).zfill(5) + "_" + expt_name.lower()+".h5"

# with h5py.File(initial_pulse,'r') as hf:
#     last_u0 = np.array(hf['uks'])[-1]
# initial_guess = last_u0


op.run_optimal_control(state_transfer = True, initial_states = [0], target_states = [1], 
                        total_time = total_time, steps = steps,max_amp = 1e-3, 
                        taylor_terms = None,is_dressed=False, 
                        convergence = convergence, reg_coeffs =  reg_coeffs,
                        plot_only_g = True,
                        states_forbidden_list = states_forbidden_list,initial_guess = initial_guess, 
                        file_name="g0_to_g1_circlgrape", data_path=data_path)

[autoreload of quantum_optimal_control.core.run_session failed: Traceback (most recent call last):
  File "C:\Users\Eesh Gupta\anaconda\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\Eesh Gupta\anaconda\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Users\Eesh Gupta\anaconda\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\Eesh Gupta\anaconda\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\e

[2, 4, 2]
starting states:
[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])]
target states:
[array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])]
[]
Hops are(2, 20, 20)
tensorflow2 grape
data saved at: 00135_g0_to_g1_circlgrape.h5
Using 10 Taylor terms and 0 Scaling & Squaring terms
Propagators initialized.
Operators weight initialized.
Vectors initialized.
Training loss initialized.
Not added train.saver functionality yet.
GPU Not available now; will integrate later
(2, 5)
no changing learning rate
inside tape
(2, 5)
inner_product
tf.Tensor(
[[ 9.9997252e-01]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 5.5210474e-03]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 

(<tf.Variable 'Variable:0' shape=(2, 5) dtype=float32, numpy=
 array([[ 7.0815266e-05, -2.0475155e-03,  5.0403741e-03,  2.0882036e-03,
         -2.6779042e-03],
        [ 3.0881379e-04,  1.1925041e-03,  2.7112127e-03, -2.6543057e-03,
         -4.3190857e-03]], dtype=float32)>,
 [],
 '00135_g0_to_g1_circlgrape.h5')

In [59]:
hf['error'][-1]

[autoreload of quantum_optimal_control.core.run_session failed: Traceback (most recent call last):
  File "C:\Users\Eesh Gupta\anaconda\lib\site-packages\IPython\extensions\autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\Eesh Gupta\anaconda\lib\site-packages\IPython\extensions\autoreload.py", line 394, in superreload
    module = reload(module)
  File "C:\Users\Eesh Gupta\anaconda\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\Eesh Gupta\anaconda\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\e

1.0

In [ ]:
op.plot_pulses()

In [ ]:
ss

In [ ]:
len(ss[0][0])

In [ ]:
op.fidelity()

In [ ]:
import os 
data_path = '/home/eag190/Multimode-Conditional-Displacements/hpc_runs/multimode_circle_grape/sample workflow/data'
file_path = 'test.h5'
file_path_f = os.path.join(data_path, file_path)
file_path_f

In [ ]:
hf = h5py.File(file_path_f, 'w')


In [ ]:
get_dressed_info

In [ ]:
w_c, v_c, dressed_id = get_dressed_info(op.H_rot())

In [ ]:
w_c

In [ ]:
v_c

In [ ]:
dressed_id