# Imports 

In [33]:
print('hi')

done
hi


C:\Users\Eesh Gupta\Documents\RU Research\Chakram\Multimode-Conditional-Displacements\hpc_runs\multimode_circle_grape\Tensorflow2_code_migration\circle_grape_v3_qoc2.py:425: SyntaxWarning: "is" with a literal. Did you mean "=="?
  else:title+=','


In [34]:
import sys
sys.path

['C:\\Users\\Eesh Gupta\\Documents\\RU Research\\Chakram\\Multimode-Conditional-Displacements\\hpc_runs\\multimode_circle_grape\\Tensorflow2_code_migration',
 'C:\\Users\\Eesh Gupta\\anaconda\\python38.zip',
 'C:\\Users\\Eesh Gupta\\anaconda\\DLLs',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda',
 '',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\qoc',
 'c:\\users\\eesh gupta\\documents\\ru research\\chakram\\quantum-optimal-control',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\locket-0.2.1-py3.8.egg',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Eesh Gupta\\anaconda\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Eesh Gupta\\.ipython',
 'C:\\Users\\Eesh Gupta\\Documents\\RU Research\\Chakram\\quantum-optimal

In [35]:
new_path= 'C:\\Users\\Eesh Gupta\\Documents\\RU Research\\Chakram\\quantum-optimal-control2'
sys.path.append(new_path)

In [36]:
%matplotlib inline
import os
import sys
import inspect
import numpy as np
from scipy.special import factorial
import h5py

#data_path = '/data'     ... data path specified later
#data_path
#initial_pulse = '../pulses/example_pulses/transmon_cat_initial_pulse.h5'
from h5py import File
import matplotlib.pyplot as plt
from pylab import*
from qutip import*

from scipy import interpolate
font = {'family' : 'normal',
        'weight' : 'normal',
        'size'   : 18}

matplotlib.rc('font', **font)


In [37]:
from quantum_optimal_control2.helper_functions.grape_functions import *
from quantum_optimal_control2.main_grape.grape import Grape
from quantum_optimal_control2 import*

In [38]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}
\newcommand{\bra}[1]{\left\langle{#1}\right|}$$

# 3DMM2 parameters

In [39]:
# chi = Peak splitting MHz
chis = 2*array([-33.1962, -0.8676]) 
kappas  = array([0,0]) # kHz

# Multimode circle grape

In [40]:
#TODO: Figure out why relative import doesn't work
from circle_grape_v3_qoc2 import *

In [41]:
transmon_levels = 2

#  Params :  $\alpha = 30.0 , \delta_c = -0.030$ GHz, $\tau = 500$ ns, $\Omega_{max} =1$ MHz

In [55]:
mode = 0
mode_levels = 1
chi,kappa = chis[mode]*1e-6,kappas[mode]*1e-6
circle_grape_params = {"chis":[chi],"kappas":[kappa],"alpha":30.0,"delta_c":-0.01}

op = multimode_circle_grape_optimal_control(mode_state_num = mode_levels,
                                            number_of_modes = 2,hparams = circle_grape_params,add_disp_kerr=False)




In [56]:
data_path = ''#'/home/eag190/Multimode-Conditional-Displacements/hpc_runs/multimode_circle_grape/sample workflow/data'

In [57]:
states_forbidden_list = []
total_time = 10.0
steps  = 5  #number of points over the total time where amplitudes will be specified

convergence = {'rate': 0.1, 'update_step': 10, 'max_iterations': 100,
               'conv_target': 3e-4, 'learning_rate_decay': 500.0}


reg_coeffs = {'dwdt': 0.1, 'd2wdt2': 1.0e-3, 'forbid_dressed': False,
               'states_forbidden_list':states_forbidden_list,
               'forbidden_coeff_list': [1.0*steps] * len(states_forbidden_list)}



initial_guess = None

ss = op.run_optimal_control(state_transfer = True, initial_states = [0], target_states = [1], 
                        total_time = total_time, steps = steps,max_amp = 1e-2, 
                        taylor_terms = None,is_dressed=False, 
                        convergence = convergence, reg_coeffs =  reg_coeffs,
                        plot_only_g = True,
                        states_forbidden_list = states_forbidden_list,initial_guess = initial_guess, 
                        file_name="g0_to_g1_circlgrape", data_path=data_path, save = True)

[6, 6, 4]
starting states:
[array([1., 0.])]
target states:
[array([0., 1.])]
[]
data saved at: 00016_g0_to_g1_circlgrape.h5
Using 4 Taylor terms and 0 Scaling & Squaring terms
hi
Propagators initialized.
Operators weight initialized.
all initialized


C:\Users\Eesh Gupta\Documents\RU Research\Chakram\quantum-optimal-control2\quantum_optimal_control2\helper_functions\data_management.py:13: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  h5py.File.__init__(self, *args, **kwargs)


In [59]:
ss

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[-0.2697316 , -0.2724801 , -0.11220679,  0.10820772,  0.0514834 ],
       [-0.88547385,  0.0985448 ,  0.23969598, -0.8612616 ,  0.32828277],
       [ 0.12648636, -0.47416863,  0.15987064, -0.38400066,  0.22851205],
       [ 0.39480907, -0.11859988,  0.14129065,  0.79053164, -0.71053535],
       [-0.16561408,  0.33163348,  0.8240745 ,  0.21020132,  0.15313447],
       [ 0.37495032, -0.01457508,  0.3439496 , -0.49408206, -0.16224556]],
      dtype=float32)>

In [65]:
weights = tf.identity(ss)
weights = tf.abs(weights)  #abs value
mode_weights = weights[2:]
mode_weights

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0.12648636, 0.47416863, 0.15987064, 0.38400066, 0.22851205],
       [0.39480907, 0.11859988, 0.14129065, 0.79053164, 0.71053535],
       [0.16561408, 0.33163348, 0.8240745 , 0.21020132, 0.15313447],
       [0.37495032, 0.01457508, 0.3439496 , 0.49408206, 0.16224556]],
      dtype=float32)>

In [77]:
num_modes = 2
num_steps = 5
# tf.reshape(mode_weights, shape = [2,num_modes, num_steps])
# mode_weights

loss = 1

sums = []
for i in range(num_modes): 
    mx_idx = i*2      #M_X weight index
    my_idx = i*2 + 1  #M_Y coeff/weight index
    s = tf.reduce_sum(mode_weights[mx_idx:my_idx])
    sums.append(s)


#loss = sum{ij = pairs of modes} s_i*s_j
for i in range(num_modes):
    for j in range(num_modes): 
        if i!=j:
            loss += sum_s1


In [78]:
tf.multiply(sums)

TypeError: Missing required positional argument

In [73]:
i = 0
mx_idx = i*2      #M_X weight index
my_idx = i*2 + 1  #M_Y coeff/weight index
s = tf.reduce_sum(mode_weights[mx_idx:my_idx +1])
s

<tf.Tensor: shape=(), dtype=float32, numpy=3.5288048>

In [75]:
mode_weights[mx_idx:my_idx + 1]

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.12648636, 0.47416863, 0.15987064, 0.38400066, 0.22851205],
       [0.39480907, 0.11859988, 0.14129065, 0.79053164, 0.71053535]],
      dtype=float32)>

In [54]:
tf.reduce_sum(weights, 0)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.67815644, 1.4951252 , 1.4989789 , 1.0796313 , 1.3043336 ],
      dtype=float32)>

In [32]:
weight

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.4392403 , 0.45825124, 0.18410705, 0.41342017, 0.31002048],
       [0.5233454 , 0.0092364 , 0.3415298 , 0.30774078, 0.54305226]],
      dtype=float32)>